#!/usr/bin/env bash
#
# Build the Landing Page using GitLab Runner.
# Makes the compiled page available at the ./public folder.
#

# Check
if ! which gitlab-runner &> /dev/null; then
  echo "Please install gitlab-runner first"
  exit 1
fi

# Do this hack while the following feature is not available at the installed
# GitLab Runner: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3246
cp .gitlab-ci-deployment.yml .gitlab-ci.yml

# Code to copy the artifact back to the working copy thanks to
# https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2226#note_396408902
gitlab-runner exec docker pages \
  --docker-volumes $(pwd)/public:/public \
  --post-build-script "rm -rf /public/* && cp -R public/* /public && chown -R $(id -u):$(id -g) /public"

# Store the build exit status
STATUS="$?"

# Restore the main CI/CD config file
git restore .gitlab-ci.yml

# Exit
exit $STATUS
