#!/usr/bin/env bash
#
# Provision the system environment needed for building a Lektor site using
#

# Check for sudo
if [ "`whoami`" != "root" ]; then
  SUDO="sudo"
fi

# Install system packages
$SUDO apt-get update
DEBIAN_FRONTEND=noninteractive $SUDO apt-get install --no-install-recommends -y \
  gettext python3-babel python3-pip git python3-inifile python3-dev python3-setuptools \
  python3-venv python3-openssl python3-cryptography #\
  # The following packages may be available from Debian bullseye onwards, but may also
  # not be compatible with the current project dependencies (such as and older Python
  # interpreter)
  #python3-babel python3-wheel lektor

# Install python packages when not using those provided by Debian
# This might also be handled at the build script using a custom requirements.txt
#pip install babel wheel lektor
